# Titanic Test

In [1]:
import pandas as pd

data = pd.read_csv("train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
print(f"Columns: {data.columns}")

Columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
print(f"Data Info: {data.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
Data Info: None

In [4]:
print("Data Description")
data.describe()

Data Description

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Some columns have Null value

In [5]:
null_check = data.isnull()
null_column_list = []

for column in data.columns:
   if any(data[column].isnull()):
       null_column_list.append(column)

print(null_column_list)

['Age', 'Cabin', 'Embarked']

### fillna: Cabin

In [6]:
data["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [7]:
data["Cabin"].isnull().value_counts()

Cabin
True     687
False    204
Name: count, dtype: int64

In [8]:
data.fillna({"Cabin": "N"}, inplace=True)
data["Cabin"] = data["Cabin"].apply(lambda x: x[0])

In [9]:
data["Cabin"].value_counts()

Cabin
N    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

### fillna(): Age

In [10]:
data["Age"].isnull().value_counts()

Age
False    714
True     177
Name: count, dtype: int64

In [11]:
print(data["Age"].max())
print(data["Age"].mean())
print(data["Age"].min())

80.0
29.69911764705882
0.42

In [12]:
mean_age = data["Age"].mean()
data.fillna({"Age": mean_age}, inplace=True)
data["Age"].isnull().value_counts()

Age
False    891
Name: count, dtype: int64

### fillna(): Embarked

In [13]:
print(data["Embarked"].value_counts())
data["Embarked"].isnull().value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Embarked
False    889
True       2
Name: count, dtype: int64

In [14]:
data.fillna({"Embarked": "N"}, inplace=True)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,N,Q

In [15]:
data.isnull().value_counts()
# There is no N/A Value.

PassengerId  Survived  Pclass  Name   Sex    Age    SibSp  Parch  Ticket  Fare   Cabin  Embarked
False        False     False   False  False  False  False  False  False   False  False  False       891
Name: count, dtype: int64

In [16]:
# get rid of unneccesary columns: PassengerId, Name, Ticket, Cabin
new_data = data.drop(["Name", "Ticket", "Cabin"], axis=1)
new_data

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.000000,1,0,7.2500,S
1,2,1,1,female,38.000000,1,0,71.2833,C
2,3,1,3,female,26.000000,0,0,7.9250,S
3,4,1,1,female,35.000000,1,0,53.1000,S
4,5,0,3,male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,13.0000,S
887,888,1,1,female,19.000000,0,0,30.0000,S
888,889,0,3,female,29.699118,1,2,23.4500,S
889,890,1,1,male,26.000000,0,0,30.0000,C
890,891,0,3,male,32.000000,0,0,7.7500,Q

In [17]:
# Labeling for Model Learning
print(new_data.info())

# Label Encoding for "Sex" and "Embarked"
from sklearn.preprocessing import LabelEncoder

features = ["Sex", "Embarked"]
for f in features:
    encoder = LabelEncoder()
    encoder.fit(new_data[f])
    new_data[f] = encoder.transform(new_data[f])

new_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB
None

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,1,22.000000,1,0,7.2500,3
1,2,1,1,0,38.000000,1,0,71.2833,0
2,3,1,3,0,26.000000,0,0,7.9250,3
3,4,1,1,0,35.000000,1,0,53.1000,3
4,5,0,3,1,35.000000,0,0,8.0500,3
...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.000000,0,0,13.0000,3
887,888,1,1,0,19.000000,0,0,30.0000,3
888,889,0,3,0,29.699118,1,2,23.4500,3
889,890,1,1,1,26.000000,0,0,30.0000,0
890,891,0,3,1,32.000000,0,0,7.7500,2

### Analysis the Passenger

In [18]:
# split data in train.csv into test and train data set
# Data will be learned by DecisionTree, LogisticRegression and Random Forest.

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# split data set
X_data = new_data.drop("Survived", axis=1)
Y_data = new_data["Survived"]
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=12)

In [20]:
dt_model = DecisionTreeClassifier()
lr_model = LogisticRegression()
rf_model = RandomForestClassifier()

model_list = [dt_model, lr_model, rf_model]
accuracy = []

for model in model_list:
    model.fit(X_train, Y_train)
    pred = model.predict(X_test)
    accuracy.append(accuracy_score(pred, Y_test))

/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [26]:
import numpy as np

result = {}
print(f"!! Normal Test Train Split")

for n in range(len(model_list)):
    result.update({model_list[n]: np.round(accuracy[n], 2)})

print(result)

!! Normal Test Train Split
{DecisionTreeClassifier(): 0.7, LogisticRegression(): 0.77, RandomForestClassifier(): 0.75}

### Each model has not high prediction score.
- Possibility of Overfit

=> Use Cross Validation with KFold and StratifiedKFold

#### KFold

In [45]:
from sklearn.model_selection import KFold


kfold = KFold(n_splits=5)
max_score_model = ""
max_score = 0

for model in model_list:    
    for train_index, test_index in kfold.split(X_data):
        X_train, X_test = X_data.iloc[train_index], X_data.iloc[test_index]
        Y_train, Y_test = Y_data.iloc[train_index], Y_data.iloc[test_index]

        model.fit(X_train, Y_train)
        accuracy = np.round(accuracy_score(model.predict(X_test), Y_test), 2)
        if max_score < accuracy:
            max_score_model = str(model.__class__).split(".")[-1][:-2]
            max_score = accuracy

print(max_score_model)
print(max_score)

/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RandomForestClassifier
0.85

#### StratifiedKFold with cross_val_score()

In [51]:
from sklearn.model_selection import cross_val_score


max_score_model = ""
max_score = 0

for model in model_list:
    scores = cross_val_score(model, X_data, Y_data, cv=5)

    for score in scores:
        if max_score < score:
            max_score_model = str(model.__class__).split(".")[-1][:-2]
            max_score = np.around(score, 2)

print(max_score_model)
print(max_score)

/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RandomForestClassifier
0.87

### Random Forest predict the test data with highest score.
- do tuning on hyper parameters with GridSearchCV

In [80]:
from sklearn.model_selection import GridSearchCV

model = DecisionTreeClassifier()

# check parameters
print(model.get_params())

{'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'random_state': None, 'splitter': 'best'}

In [90]:
params = {"max_depth": range(10), "max_leaf_nodes": range(10), "min_samples_leaf": range(10)}

# Define GridSearchCV
gscv = GridSearchCV(model, param_grid=params, scoring="accuracy", cv=5)
gscv.fit(X_train, Y_train)

/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning:
1760 fits failed out of a total of 5000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of DecisionTreeClassifier must be an int in the range [1, inf) or None. Got 0 instead.

--------------------------------------------------------------------------------
450 fits failed with the following error:
Traceback (most recent call last):
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_leaf_nodes' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or None. Got 0 instead.

--------------------------------------------------------------------------------
450 fits failed with the following error:
Traceback (most recent call last):
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_leaf_nodes' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or None. Got 1 instead.

--------------------------------------------------------------------------------
360 fits failed with the following error:
Traceback (most recent call last):
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_leaf' parameter of DecisionTreeClassifier must be an int in the range [1, inf) or a float in the range (0.0, 1.0). Got 0 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/luna-negra/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
        nan 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
        nan 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
        nan 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013        nan 0.7135034
 0.7135034  0.78392593 0.78392593 0.78392593 0.77973013 0.77973013
 0.77973013 0.77973013        nan 0.71209495 0.71209495 0.78392593
 0.78392593 0.78392593 0.77973013 0.77973013 0.77973013 0.77973013
        nan 0.71209495 0.71209495 0.78392593 0.78392593 0.78392593
 0.77973013 0.77973013 0.77973013 0.77973013        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356        nan 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013        nan 0.7176992  0.7176992  0.78953019
 0.78953019 0.78953019 0.78533438 0.78533438 0.78113858 0.76155816
        nan 0.70372304 0.70372304 0.77414557 0.77414557 0.77414557
 0.76994977 0.76994977 0.76015956 0.76295676        nan 0.70512164
 0.70512164 0.77554417 0.77554417 0.77554417 0.77134837 0.77134837
 0.75176795 0.75176795        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356        nan 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
        nan 0.7176992  0.7176992  0.78953019 0.78953019 0.78953019
 0.78533438 0.78533438 0.78113858 0.76155816        nan 0.70372304
 0.70372304 0.77132867 0.77132867 0.77132867 0.76713287 0.76713287
 0.75734266 0.76853147        nan 0.69950753 0.69950753 0.76993007
 0.76993007 0.76993007 0.77551463 0.77692308 0.75874126 0.76576381
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
        nan 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013        nan 0.7176992
 0.7176992  0.78953019 0.78953019 0.78953019 0.78533438 0.78533438
 0.78113858 0.76155816        nan 0.70372304 0.70372304 0.77132867
 0.77132867 0.77132867 0.76713287 0.76713287 0.75734266 0.76853147
        nan 0.69950753 0.69950753 0.77133852 0.77133852 0.77133852
 0.77692308 0.77833153 0.76014971 0.75878066        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356        nan 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013        nan 0.7176992  0.7176992  0.78953019
 0.78953019 0.78953019 0.78533438 0.78533438 0.78113858 0.76155816
        nan 0.70372304 0.70372304 0.77132867 0.77132867 0.77132867
 0.76713287 0.76713287 0.75734266 0.76853147        nan 0.69950753
 0.69950753 0.77133852 0.77133852 0.77133852 0.77692308 0.77833153
 0.76014971 0.75878066        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703        nan 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356        nan 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
        nan 0.7176992  0.7176992  0.78953019 0.78953019 0.78953019
 0.78533438 0.78533438 0.78113858 0.76155816        nan 0.70372304
 0.70372304 0.77132867 0.77132867 0.77132867 0.76713287 0.76713287
 0.75734266 0.76853147        nan 0.69950753 0.69950753 0.77133852
 0.77133852 0.77133852 0.77692308 0.77833153 0.76014971 0.75878066
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.78254703 0.78254703 0.78254703
 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703 0.78254703
        nan 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822        nan 0.77135822
 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822 0.77135822
 0.77135822 0.77135822        nan 0.75728356 0.75728356 0.75728356
 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356 0.75728356
        nan 0.77973013 0.77973013 0.77973013 0.77973013 0.77973013
 0.77973013 0.77973013 0.77973013 0.77973013        nan 0.7176992
 0.7176992  0.78953019 0.78953019 0.78953019 0.78533438 0.78533438
 0.78113858 0.76155816        nan 0.70372304 0.70372304 0.77132867
 0.77132867 0.77132867 0.76713287 0.76713287 0.75734266 0.76853147
        nan 0.69950753 0.69950753 0.77133852 0.77133852 0.77133852
 0.77692308 0.77833153 0.76014971 0.75878066]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(0, 10),
                         'max_leaf_nodes': range(0, 10),
                         'min_samples_leaf': range(0, 10)},
             scoring='accuracy')

In [91]:
# Check the best Params
print(gscv.best_params_)

{'max_depth': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3}

In [96]:
# Check the best score
print("---")
print(f"GridSearchCV Best Score: {np.round(gscv.best_score_, 2)}")
print("---")

---
GridSearchCV Best Score: 0.79
---

In [98]:
# Get the best Param and apply
tuned_model = gscv.best_estimator_
pred = tuned_model.predict(X_test)
print("---")
print(f"Model with Best HyperParameters Prediction: {np.around(accuracy_score(pred, Y_test), 2)}")
print("---")

---
Model with Best HyperParameters Prediction: 0.87
---